baseURL                  = "https://federicocircosta.it"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Federico Circosta"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "f.ico"
    homepage             = "home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Federico Circosta © 2021"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Federico Circosta"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/background.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    # overlay = "rgba(0, 0, 0, 0.4)" # optional

#[[params.mainMenu]]
#    link = "posts"
#    text = "posts"

#[[params.mainMenu]]
#    link = "gallery"
#    text = "gallery"

[[params.mainMenu]]
    link = "https://vimeo.com/federicocircosta"
    text = "video"

[[params.mainMenu]]
    link = "about"
    text = "chi?"

[imaging]
    quality = 80
